version: '2'

services:
  desk-sharing-backend:
    image: kaulsdorfit/desk-sharing:latest
    environment:
      - NODE_ENV=production
    networks:
      - deskSharing
    depends_on:
      - desk-sharing-mongodb

  desk-sharing-mongodb:
    image: mongo:3.6
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./mongo_data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--journal","--smallfiles" ]
    environment:
      - AUTH=no
    networks:
      - deskSharing

networks:
  deskSharing:
