version: '2'

services:
  desk-sharing-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - ./backend/:/usr/app/
    environment:
      - NODE_ENV=development
    networks:
      - deskSharing
    depends_on:
      - desk-sharing-mongodb

  desk-sharing-mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./db_data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--journal","--smallfiles" ]
    environment:
      - AUTH=no
    networks:
      - deskSharing

networks:
  deskSharing:
