version: '2'

services:
  desk-sharing-backend:
    image: kaulsdorfit/desk-sharing:latest
    environment:
      - VIRTUAL_HOST=desk-sharing.dbt.db.de
      - VIRTUAL_PORT=8080
      - NODE_ENV=development
    networks:
      - deskSharing
      - nginx-proxy
    depends_on:
      - desk-sharing-mongodb

  desk-sharing-mongodb:
    image: mongo:3.6
    ports:
      - 27117:27017
    restart: always
    volumes:
      - /srv/docker-volumes/forms_data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--journal","--smallfiles" ]
    environment:
      - AUTH=no
    networks:
      - deskSharing

networks:
  default:
  nginx-proxy:
    external:
      name: nginx-proxy
