# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/checkout@v2
    - name: build desk sharing backend
      run:  |
        cd desk-sharing/backend
        yarn install --frozen-lockfile && yarn build
    - name: build desk-sharing gui
      run: |
        cd desk-sharing/gui
        yarn install --frozen-lockfile && yarn build
